### ISSUE TITLE
新用户已经注册成功了返回的用户ID但是当我登录进入的时候提示错误

### ISSUE THREAD

**Issue by dotcool** [wildfirechat/flutter_imclient#14]
`I/flutter (24794): userId:676137
E/MethodChannel#flutter_imclient(24794): Failed to handle method call
E/MethodChannel#flutter_imclient(24794): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String cn.wildfirechat.model.ProtoUserInfo.getUid()' on a null object reference
E/MethodChannel#flutter_imclient(24794): 	at cn.wildfirechat.flutter_imclient.FlutterImclientPlugin.convertProtoUserInfo(FlutterImclientPlugin.java:1434)
E/MethodChannel#flutter_imclient(24794): 	at cn.wildfirechat.flutter_imclient.FlutterImclientPlugin.onMethodCall(FlutterImclientPlugin.java:573)
E/MethodChannel#flutter_imclient(24794): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter_imclient(24794): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_imclient(24794): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#flutter_imclient(24794): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_imclient(24794): 	at android.os.MessageQueue.next(MessageQueue.java:386)
E/MethodChannel#flutter_imclient(24794): 	at android.os.Looper.loop(Looper.java:175)
E/MethodChannel#flutter_imclient(24794): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/MethodChannel#flutter_imclient(24794): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_imclient(24794): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/MethodChannel#flutter_imclient(24794): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)`

**Comment by dotcool** [comment]
我看后台日志是这个错误 ` ERROR MemorySessionStore 297  - Can't find the session for client <b02849e20a057b851615892600893>
`
